CREATE TABLE [dbo].[Notification]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[Sms] BIT DEFAULT 0 NOT NULL,
	[Mail] BIT DEFAULT 0 NOT NULL,
	[UserId] INT NOT NULL
	FOREIGN KEY (UserId) REFERENCES [User](Id)
)
