
CREATE TABLE [dbo].[User]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
	[Name] VARCHAR(50) NOT NULL,
	Email VARCHAR(150) NOT NULL UNIQUE,
	Passwd VARCHAR(200) NOT NULL,
	Picture VARBINARY(4),
	Role VARCHAR(20) 
)
