CREATE TABLE [dbo].[PictureProfil]
(
	[Id] INT NOT NULL IDENTITY PRIMARY KEY,
	[Picture] VARBINARY(MAX),
	[CreateAt] DATETIME NOT NULL,
	[ModifiedAt] DATETIME NOT NULL,
	[IdUser] INT NOT NULL
	FOREIGN KEY (IdUser) REFERENCES [User](Id)
)
