CREATE TABLE [dbo].[Category]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[Shohin] BIT DEFAULT 0 NOT NULL,
	[Mame] BIT DEFAULT 0 NOT NULL,
	[Chokkan] BIT DEFAULT 0 NOT NULL,
	[Moyogi] BIT DEFAULT 0 NOT NULL,
	[Shakan] BIT DEFAULT 0 NOT NULL,
	[Kengai] BIT DEFAULT 0 NOT NULL,
	[HanKengai] BIT DEFAULT 0 NOT NULL,
	[Ikadabuki] BIT DEFAULT 0 NOT NULL,
	[Neagari] BIT DEFAULT 0 NOT NULL,
	[Literati] BIT DEFAULT 0 NOT NULL,
	[YoseUe] BIT DEFAULT 0 NOT NULL,
	[Ishitsuki] BIT DEFAULT 0 NOT NULL,
	[Kabudachi] BIT DEFAULT 0 NOT NULL,
	[Kokufu] BIT DEFAULT 0 NOT NULL,
	[Yamadori] BIT DEFAULT 0 NOT NULL,
	[Perso] VARCHAR(150),
	[BonsaiId] INT NOT NULL,
	FOREIGN KEY (BonsaiId) REFERENCES [Bonsai](Id)
)
