CREATE TABLE [dbo].[Style]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	Chokkan BIT DEFAULT 0 NOT NULL,
	Moyogi BIT DEFAULT 0 NOT NULL,
	Shakan BIT DEFAULT 0 NOT NULL,
	Kengai BIT DEFAULT 0 NOT NULL,
	HanKengai BIT DEFAULT 0 NOT NULL,
	Ikadabuki BIT DEFAULT 0 NOT NULL,
	Neagari BIT DEFAULT 0 NOT NULL,
	Bunjin BIT DEFAULT 0 NOT NULL,
	YoseUe BIT DEFAULT 0 NOT NULL,
	Ishitsuki BIT DEFAULT 0 NOT NULL,
	Kabudachi BIT DEFAULT 0 NOT NULL,
	Bankan BIT DEFAULT 0 NOT NULL,
	Korabuki BIT DEFAULT 0 NOT NULL,
	Yamadori BIT DEFAULT 0 NOT NULL,
	Ishituki BIT DEFAULT 0 NOT NULL,
	[Perso] VARCHAR(150),
	[BonsaiId] INT NOT NULL
	FOREIGN KEY (BonsaiId) REFERENCES [Bonsai](Id)
)
