CREATE TABLE [dbo].[Post]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[Title] VARCHAR(50) NOT NULL,
	[Description] VARCHAR(200) NOT NULL,
	[Content] VARCHAR(MAX) NOT NULL,
	[CreateAt] DATETIME NOT NULL,
	[ModifiedAt] DATETIME,
	[IdUser] INT NOT NULL
	FOREIGN KEY(IdUSer) REFERENCES [User](Id)
)
